.upignore
up.json

Basic support for deploying via https://github.com/apex/up:
Currently deployed here:
https://wg7c5oygsl.execute-api.us-west-2.amazonaws.com/development/
This deployment doesn't actually work that well, because `go-httpbin` doesn't know how to handle the `/development` URL prefix that seems to be unavoidable until a custom domain is configured.
TODO:
[1]: http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html

Deploy using apex/up

---

httpbin/helpers.go

This fixes `parseBody()` when the `Content-Type` header is something like `application/x-www-form-urlencoded; charset=utf-8`.

Fix body parsing with longer form content-type headers

---

httpbin/handlers.go
httpbin/handlers_test.go

RFC 2616 (HTTP/1.1) says in the ["3.5 Content Codings" section](https://tools.ietf.org/html/rfc2616#section-3.5) this about deflate:
> The "zlib" format defined in RFC 1950 [31] in combination with the "deflate" compression mechanism described in RFC 1951 [29].
The [zlib package](https://golang.org/pkg/compress/zlib/#pkg-overview) from Go's standard library imlpements RFC 1950 and it also [uses](https://golang.org/src/compress/zlib/writer.go#L15) the [flate package](https://golang.org/pkg/compress/flate/#pkg-overview) internally, which implements RFC 1951.
I'm not sure if you maintain httpbingo.org, but opening https://httpbingo.org/deflate with Firefox or Chrome produces an error, I assume because of this. For some reason `curl -v --compressed https://httpbingo.org/deflate` works …

Fix deflate encoded responses

---

httpbin/handlers_test.go
httpbin/helpers.go
httpbin/httpbin.go
httpbin/middleware.go

This is a rebased version of https://github.com/mccutchen/go-httpbin/pull/4 with a fixed middleware order.
At the moment `OPTIONS` requests return `405 Method Not Allowed` error and `HEAD` is not supported at all.

Add support for HEAD and fix the OPTIONS HTTP method

---

now.json

Just experimenting with https://zeit.co/now as an alternative to https://up.docs.apex.sh/, mostly to get away from mysterious AWS API Gateway complexity/opacity/weirdness as described in https://github.com/mccutchen/go-httpbin/pull/3#issuecomment-375367129.

Deploy via `now` instead of `up`

---

cmd/go-httpbin/main.go
httpbin/handlers_test.go
httpbin/httpbin.go
httpbin/httpbin_test.go
httpbin/middleware.go

This change allows users to specify their own logger for an `HTTPBin` instance, as long as it implements this minimal interface (which matches [the stdlib's `log.Logger`][1]):
```go
// Logger is a minimal logging interface
type Logger interface {
Printf(format string, v ...interface{})
}
```
When using go-httpbin as a library (e.g. for unit tests), the default logger now _silently discards all messages_.
The `go-httpbin` binary & Docker container, on the other hand, will generate log messages like so:
```
./dist/go-httpbin
go-httpbin listening on 0.0.0.0:8080
time="2019-01-14T17:04:54.5177" status=200 method="GET" uri="/" size_bytes=11271 duration_ms=0.55
time="2019-01-14T17:04:59.048" status=418 method="GET" uri="/status/418" size_bytes=13 duration_ms=0.20
time="2019-01-14T17:05:03.1649" …
```

Support pluggable logger

---

README.md
cmd/go-httpbin/main.go

go-httpbin is great and I use it for demos locally. Thanks for building it. 
I ran into a requirement of using https with go-httpbin and added support for the same by adding -host, -https-cert and -https-key options. Updated README with command line and docker examples.

Adding support for specifying host and https

---

.travis.yml
cmd/go-httpbin/main.go
httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go
httpbin/httpbin.go

- Added code and test cases for /uuid endpoint
- Updated httpbin.go to handle ListenAndServe errors - useful because in the current state, the code silently fails in case the server is rerun with the same host and port combination.

Add support for /uuid

---

README.md
httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go

Two things here:
1. Test all base64 error cases
2. Just let `uuidv4()` panic if it can't read enough random data (which is a legitimately exceptional circumstance)

Get code coverage back up

---

.travis.yml
Dockerfile
Makefile
cmd/maincmd/main.go

Ensure that go-httpbin allows any in-flight requests to finish before shutting down.
I'm not sure how best to unit test this, so for now I've just tested it manually like so:
1. In one shell, `make run`
2. In another shell, `curl -s -v localhost:8080/delay/10 >/dev/null` to make a 10 second request
3. In a third shell, `kill -s TERM $(ps aux | grep go-httpbin | grep -v grep | awk '{print $2}')` to tell the server to shut down
This results in these logs from the server, showing that the request was allowed to finish before it exited:
```
time="2019-10-03T08:22:28.5216" msg="received signal terminated, shutdown started"
time="2019-10-03T08:22:35.2511" status=200 method="GET" uri="/delay/10" size_bytes=204 duration_ms=10000.60
time="2019-10-03T08:22:35.5227" msg="shutdown finished"
```
and …

Shut down gracefully

---

httpbin/helpers.go

Given link was pointing to localhost:8080 instead of official golang.org

typo in docs link

---

static/index.html

Was a little confused when the fork's home page contained links to the original version of `httpbin`, not sure if these changes are in the right place, I was looking for a `/docs` or `/html` folder.

static/index.html: change links from httpbin.org to httpbingo.org

---

.github/workflows/cleanup.yaml

In an unsurprising turn of events, there was a mistake in the cleanup workflow from #32.

Fix staging deploy cleanup workflow

---

app.yaml

Per #35, httpbingo.org requiring https for all requests actually reduces its utility as a general purpose http testing tool.  Here we tweak the App Engine deployment configuration to require https only for requests to the index page, but not to any other resources.
My thought is that it's still worthwhile to use https by default, especially for users who end up at httpbingo.org in a web browser, but we'll see whether this actually works the way I'm hoping it will.

Allow serving non-index pages via plain HTTP (fixes #35)

---

Dockerfile
Makefile
bin/gcloud

Move from Google's managed App Engine platform to their managed Cloud Run platform, to unbreak the endpoints that stream responses. Fixes #40 and #41.
https://httpbingo.org is now served from Cloud Run (pending DNS propagation).  This curl command should confirm whether it's now working as expected:
```
curl 'https://httpbingo.org/drip?numbytes=10&duration=10' --no-buffer
```
Still TODO (but maybe in a follow-up):

Deploy to Google Cloud Run

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/httpbin.go

This is the rest of the fix for #40, to bring our `/drip` implementation more in line with that of httpbin.org's:
- Set `Content-Length` header
- Match default parameter values
- Send status code before any delay
cc @StefanKarpinski

Make /drip more compatible with original httpbin's implementation

---

httpbin/handlers_test.go
httpbin/middleware.go

This fixes a panic caused by `HEAD` requests to endpoints that stream responses (e.g. `/drip`, `/stream`, etc):
```
2020/09/30 15: 59:21 http: panic serving 169.254.8.129:57237: interface conversion: *httpbin.headResponseWriter is not http.Flusher: missing method Flush
at net/http.(*conn).serve.func1 (server.go:1801)
at panic (/usr/local/go/src/runtime/panic.go:975)
at github.com/mccutchen/go-httpbin/httpbin.(*HTTPBin).Drip (handlers.go:543)
at net/http.HandlerFunc.ServeHTTP (server.go:2042)
at net/http.(*ServeMux).ServeHTTP (server.go:2417)
at github.com/mccutchen/go-httpbin/httpbin.limitRequestSize.func1 (middleware.go:57)
at net/http.HandlerFunc.ServeHTTP (server.go:2042)
at github.com/mccutchen/go-httpbin/httpbin.preflight.func1 (middleware.go:30)
at net/http.HandlerFunc.ServeHTTP …
```

Fix handling of HEAD requests for streaming responses

---

httpbin/handlers.go
httpbin/handlers_test.go

This fixes the `/status` endpoint's handling of [300 Multiple Choice](https://httpstatuses.com/300) and [308 Permanent Redirect](https://httpstatuses.com/308) responses, per @cbeamond's reports in #46 and #47.

Better redirects

---

httpbin/handlers_test.go
httpbin/helpers.go

Instead of returning the contents of `X-Forwarded-For` verbatim as a (likely) comma-separated string of IP addresses, extract just the client IP.

Update /ip endpoint to return single origin IP

---

.github/workflows/continuous_delivery.yaml
.github/workflows/lint.yaml
README.md

Was wondering why the github actions weren't running on #68, this should do it.

Fix lingering references to the old master branch

---

httpbin/handlers.go
httpbin/handlers_test.go

See https://github.com/mccutchen/go-httpbin/issues/67 for details.  Demonstration of the issue, using the example URL provided (https://httpbingo.org/base64/ZXhhbXBsZS5vcmciPjxzdmcvb25sb2FkPXByb21wdCgneHNzJyk+):
With the fix locally:
Thanks for the report @danbf!

Close XSS issue in /base64 endpoint (fixes #67)

---

Makefile
README.md
cmd/go-httpbin/main.go
httpbin/handlers.go
httpbin/handlers_test.go
httpbin/httpbin.go
httpbin/static/index.html

This adds a new /hostname endpoint as originally proposed in https://github.com/mccutchen/go-httpbin/pull/66.
In this implementation, it exposes a dummy hostname by default, and only exposes the real hostname (via `os.Hostname()`) if the `-use-real-hostname` flag or `USE_REAL_HOSTNAME` env vars are set to true, which should make this safe for users to adopt without unintentionally exposing details of the underlying infrastructure unless they want to.
cc @uromahn @x70b1

Add /hostname endpoint

---

.github/workflows/lint.yaml
.github/workflows/test.yaml
Dockerfile

I updated golang to 1.19.
Other than that I replaced `CMD` with `ENTRYPOINT`. This container image is a very good example for the difference between booth settings. You can now use the `CMD` for command line options. Example:
```
nerdctl run mccutchen/go-httpbin -use-real-hostname
```

Update golang to 1.19

---

.github/workflows/release.yaml

Let's automate this chore.
Unfortunately, I don't know of a good way to test this, so I guess I'll wait for the next release and see what breaks.  I'm suspicious, in particular, of my ability to push directly to ghcr.io with the default permissions given to GH Actions on this repo, but we'll see!

Add workflow to push docker images for new releases

---

httpbin/digest/digest.go
httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go
httpbin/httpbin.go

We were not explicitly testing the behavior of some HTTP verb endpoints like `/put`, `/patch`, and `/delete`, because they (currently) share an underlying handler with `/post` which is thoroughly tested.
The addition of the `/anything` endpoint in #83 made me realize a bit more explicit test coverage would be good, so here we're landing a bit of a refactoring of the test suite to generate tests for all of those endpoints.
Along the way, the more thorough test coverage uncovered a compatibility issue with the original httpbin implementation, which supports `DELETE` requests with bodies.  We handle that by tricking the stdlib net/http machinery into parsing those request bodies.

More comprehensive tests for HTTP verb endpoints

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go

- Return for GET to /anything as httpbin does. While not common, it is possible to have bodies in GET requests with HTTP/1.0
- Don't escape HTML in JSON to reproduce httpbin behavior
- Always return a newline at end of JSON response
Great project, tests complete much faster than using python httpbin :) I am running [ftw](https://github.com/coreruleset/go-ftw), a test suite for WAFs with expectations based on httpbin. Many many tests including uncommon ones like HTTP/1.0 so hopefully it's helped squeeze out remaining incompatibilities. With this PR, the suite passes fine.
FYI, integrating with the code from this PR in https://github.com/corazawaf/coraza-proxy-wasm/pull/77

Improve compatibility with httpbin for requests with bodies

---

.github/workflows/release.yaml

I now know from wrestling with this in another repo (https://github.com/mccutchen/kafka-lite/pull/6, https://github.com/mccutchen/kafka-lite/pull/8, https://github.com/mccutchen/kafka-lite/pull/9, https://github.com/mccutchen/kafka-lite/pull/10) that the release automation added in #87 is going to break on pushes to ghcr.io.

Disable pushes to ghcr.io on release

---

httpbin/handlers.go

This is getting a bit into micro-optimization territory, but in the course of working on a bit of cleanup I realized there might be something to gain from making the `/status` endpoint a bit more efficient by initializing all the data it needs once instead of on every request.
Results, from a set of highly unscientific vegeta benchmark runs on my laptop (3x per version):
```
$ echo "GET http://localhost:8080/status/200" | vegeta attack -rate 0 -max-workers 100 -duration 30s | vegeta report
Requests      [total, rate, throughput]         599239, 19973.51, 19971.04
Duration      [total, attack, wait]             30.005s, 30.002s, 3.711ms
Latencies     [min, mean, 50, 90, 95, 99, max]  100.397µs, 3.434ms, 2.52ms, 7.487ms, 9.388ms, 14.141ms, 35.997ms
Bytes In      [total, mean] …
```

Extract inline vars from the status handler

---

Makefile

Ran into an issue where the makefile did not think it needed to rebuild anything during a `make watch` session, which led to a decent amount of confusion.  My make skills are not up to digging into how to handle this better and `go build` is fast enough, so let's just rebuild every time.

build: stop being clever about when to rebuild

---

README.md
cmd/go-httpbin/main.go
httpbin/handlers.go
httpbin/handlers_test.go
httpbin/httpbin.go

The `/redirect-to` endpoint currently acts as an open redirect, which is bad for any go-httpbin instance exposed to the public internet.
This allows configuring an allowlist of domains to which traffic can be redirected, which should address https://github.com/mccutchen/go-httpbin/security/code-scanning/4.
While we're at it, add some specific production configuration guidance to the README.

Allow restricting redirect destinations

---

httpbin/cmd/cmd.go
httpbin/cmd/cmd_test.go

Fix a small regression in #98, best illustrated by this diff:
```diff
--- help.before	2022-11-13 11:43:51.000000000 -0500
+++ help.after	2022-11-13 11:43:56.000000000 -0500
@@ -1,4 +1,4 @@
-Usage:
+Usage of go-httpbin:
-allowed-redirect-domains string
Comma-separated list of domains the /redirect-to endpoint will allow
-host string
```

cmd: fix help output

---

httpbin/handlers.go
httpbin/handlers_test.go

Make the error message when a forbidden destination is given to `/redirect-to`, to help users better understand what allowed usage looks like.  Motivated by @jonpryor's report in https://github.com/mccutchen/go-httpbin/issues/103.
Before: 
```
$ curl http://localhost:8080/redirect-to?url=https://google.com
Forbidden redirect URL. Be careful with this link.
```
After:
```
$ curl http://localhost:8080/redirect-to?url=https://google.com
Forbidden redirect URL. Please be careful with this link.
Allowed redirect destinations:
- example.com
- example.org
```

More helpful error when allowed redirect domains are defined

---

httpbin/handlers.go
httpbin/handlers_test.go

When go-httpbin is used as a test service and accessed through a gateway, 404 may be returned due to incorrect configuration of the gateway. 
By optimizing the response content, you can clearly know whether the 404 is returned by the gateway or go-httpbin.

feat: ensure that 404 responses indicate that they originate from go-httpbin

---

.codecov.yml
.github/workflows/test.yaml

Started seeing a deprecation warning on codecov comments ([e.g.](https://github.com/mccutchen/go-httpbin/pull/109#issuecomment-1408556422)):
> 📣 This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Will+McCutchen)
So, I installed the GitHub App integration.  Not sure what else is required, but this also seems like a good time to bump the GitHub Action we're using to the latest release.
Let's see what happens, I guess?

ci: update codecov action

---

httpbin/handlers.go
httpbin/handlers_test.go

Fixes #112.
BREAKING CHANGE: Requests for zero bytes now actually return zero bytes. Requests for negative numbers of bytes are now rejected.

fix: properly handle /bytes/0

---

httpbin/handlers_test.go
httpbin/helpers.go

Also, switch to URL-safe base64 instead of standard base64, for compatibility with original httpbin.
Fixes #118.

fix: correctly handle padded base64 input

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/responses.go

```console
$ curl -s https://httpbingo.org/anything | jq .method                                                                                                        9:31PM
null
$ curl -s https://httpbin.org/anything | jq .method
"GET"
$ curl -s http://0.0.0.0:8080/anything | jq .method
"GET"
```
This was mentioned in #6, but then not listed in #91
- I took the highly technical testing approach of adding a test for `Method` anywhere in `handlers_test.go` that mentioned `Args`; do you desire more tests? fewer tests?
- Anywhere else I should add this field that I didn't already?
For what it's worth, I discovered this when working on upgrading the testing for our [httpsnippet library](https://github.com/readmeio/httpsnippet); I wanted to use `go-httpbin` but our tests expect the method …

feat: add method property to responses

---

httpbin/helpers.go

When a request to `/anything` has an empty body, the `data` field of the output should be the empty string. Currently, `go-httpbin is returning `data:application/octet-stream;base64,`.
- Should the output actually be null? That would match `files`, `form`, and `json`, but also would require deeper changes since `Data` is stored as a string not a pointer, and I didn't want to mess with things any more than I had to. An empty string works fine for my purposes
- how can I test this PR? I tried but I got confused by the TestAnything method
- all the current tests pass under this change
This PR closes #124. Before:
```
$ curl -s 'http://0.0.0.0:8080/anything?one=two'
{
"args": {
"one": [
"two"
]
},
"headers": {
"Accept": [
"*/*"
],
"Host": [
"0.0.0.0:8080"
],
"User-Agent": [
"curl/7.88.1"
]
}, …
```

fix: don't update Data when body is empty

---

httpbin/helpers.go
httpbin/helpers_test.go

`go-httpbin` was incorrectly returning `http` as the scheme for its URL if you ran it with TLS specified via `HTTPS_CERT_FILE` and `HTTPS_KEY_FILE`. Update it to return https as the scheme in this case by checking if `r.TLS` is not nil
Before:
```
$ mkcert test
$ docker run -e HTTPS_CERT_FILE='/tmp/test.pem' -e HTTPS_KEY_FILE='/tmp/test-key.pem' -p 8080:8080 -v $(pwd):/tmp mccutchen/go-httpbin
$ curl -sk https://localhost:8080/get | jq -r .url
http://localhost:8080/get
```
After (TLS):
```
$ docker run -e HTTPS_CERT_FILE='/tmp/test.pem' -e HTTPS_KEY_FILE='/tmp/test-key.pem' -p 8080:8080 -v $(pwd):/tmp llimllib/go-httpbin
$ curl -sk https://localhost:8080/get | jq -r .url
https://localhost:8080/get
```
After (no TLS):
```
$ docker run -p 8080:8080 llimllib/go-httpbin
$ curl -sk …
```

Return https if r.TLS is not nil

---

httpbin/handlers_test.go
httpbin/helpers.go
httpbin/helpers_test.go

- populate files slice on multipart/form-data request
- it was already present, but just wasn't filled out anywhere
- Is my test sufficient?
- How I'm currently integration testing this is by running this script:
```bash
printf "Hello World\n" > hello.txt
curl -s --request POST \
--url http://0.0.0.0:8080/anything \
--header 'content-type: multipart/form-data' \
--form foo=@hello.txt \
--form 'bar=Bonjour le monde' | jq .files
```
against a development server and expecting this output:
```json
{
"foo": [
"Hello World\n"
]
},
```

populate files slice on multipart/form submission

---

httpbin/handlers_test.go
httpbin/helpers.go
httpbin/helpers_test.go

fix: include Transfer-Encoding when echoing request headers

---

go.mod
httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go
httpbin/helpers_test.go
httpbin/responses.go
internal/testing/assert/assert.go
internal/testing/must/must.go

In the course of validating #125, we discovered that using the stdlib's [`httptest.ResponseRecorder`][0] mechanism to drive the vast majority of our unit tests led to some slight brokenness due to subtle differences in the way those "simulated" requests are handled vs "real" requests to a live HTTP server, as [explained in this comment][1].
That prompted me to do a big ass refactor of the entire test suite, swapping httptest.ResponseRecorder for interacting with a live server instance via [`httptest.Server`][2].
This should make the test suite more accurate and reliable in the long run by ensuring that the vast majority of tests are making actual HTTP requests and reading responses from the wire.
Note that updating these tests also uncovered a few minor bugs in existing handler code, …

Refactor test suite to make real requests to a real server

---

Makefile
httpbin/handlers.go
httpbin/handlers_test.go
internal/testing/assert/assert.go

This started with me wading into the `/drip` endpoint to add `Server-Timing` trailers as suggested in https://github.com/mccutchen/go-httpbin/issues/72.
In making those changes, I discovered that the standard golang net/http server we're building on only supports sending trailers when the response is written using `Content-Encoding: chunked`.  Initially, I thought it would be reasonable for this endpoint, which is designed to stream writes to the client, to switch over to a chunked response, but upon further consideration I don't think that's a good idea.  So I'll defer adding trailers to some later work.
But, in thinking this through (and fighting with the unit tests already in place for drip), I realized that the `/drip` endpoint had room for improvement, if we think about it as an …

Improve /drip semantics

---

httpbin/handlers_test.go

A set of test suite improvements following up on #131:
- Make sure we always fully consume and close response bodies, to allow the shared HTTP client to reuse connections to the local test server whenever possible
- Make order of arguments to equality assertions consistent, so failed test output makes sense

Always consume body in tests

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go
httpbin/responses.go

Cleans up inconsistent and incorrect content types for plain text, html, JSON, and binary responses.

Standardize common content types

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go
httpbin/httpbin.go
httpbin/middleware.go
httpbin/middleware_test.go
httpbin/options.go
httpbin/responses.go
internal/testing/assert/assert.go

Standardize on structured JSON error responses everywhere we can, with only one exception where the error is a warning for humans to read.
Fixes #108 by adding a check to every request in the test suite to ensure that errors are never served with a Content-Type that might enable XSS or other vulnerabilities.
While we're at it, continue refining the test suite and further adopting some of the testing helpers added in #131.

Improve and standardize error handling

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go

In testing out error handling after #135, I happened to stumble across an unexpected panic for requests like `/status/1024` where the user-provided status code is outside the legal bounds.  So, here we take a quick pass to ensure we're parsing and validating status codes the same way everywhere.

Consistently parse and validate user-provided status codes

---

httpbin/handlers_test.go

Issue #129 prompted me to look into how go-httpbin actually handles incoming requests that specify an `Expect: 100-continue` header.  Here we add additional unit tests to explicitly codify the, uh, _expected_ behavior for those requests.
Note that the Go stdlib http client and server implementations have automagical `Expect: 100-continue` handling (see below), which means these particular tests need to be written at a slightly lower level, by directly writing to and reading from the underlying TCP connection.
Now, it may well be that the the moving parts (e.g. load balancers) between a client and the instances of go-httpbin deployed at https://httpbingo.org intervene and change this behavior, but these tests give me some confidence that, at least when such requests are made directly to …

Add tests for correct handling of Expect: 100-continue

---

README.md
httpbin/cmd/cmd.go
httpbin/cmd/cmd_test.go
httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go
httpbin/helpers_test.go
httpbin/httpbin.go
httpbin/options.go

I want to deploy go-httpbin to Alibaba Cloud Function Compute (A Serverless Runtime), But in FC, the Server will add some custom header on the request headers:
for example:
So I add this logic to process unused headers:
```golang
opts := []httpbin.OptionFunc{
httpbin.WithMaxBodySize(cfg.MaxBodySize),
httpbin.WithMaxDuration(cfg.MaxDuration),
httpbin.WithObserver(httpbin.StdLogObserver(logger)),
httpbin.WithExcludeHeaders("x-ignore-*,x-info-this-key"),
}
```

feat: allow filtering incoming request headers

---

httpbin/handlers_test.go
httpbin/helpers.go
httpbin/static/index.html

As reported in #152, the `/base64` endpoint can only decode the "URL-safe" base64 encoding, but the error it returns is not very useful if you're not already familiar with different base64 encoding variants.
Here we follow [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle) and accept either the URL-safe or standard encodings, while continuing to use the URL-safe variant when encoding ourselves.
Fixes #152.

fix: /base64 endpoint decodes both URL-safe and standard b64 encodings

---

.dockerignore
.github/workflows/lint.yaml
Makefile
cmd/go-httpbin/main.go
examples/custom-instrumentation/main.go
httpbin/cmd/cmd.go
httpbin/doc.go
httpbin/handlers.go
httpbin/helpers.go
httpbin/options.go
internal/testing/assert/assert.go
internal/testing/must/must.go

- Adopt [revive](https://github.com/mgechev/revive) as the local linter used by `make lint`
- Update to latest golangci-lint releases for CI

chore: update linting configuration

---

httpbin/handlers.go
httpbin/websocket/websocket.go
httpbin/websocket/websocket_autobahn_test.go
httpbin/websocket/websocket_test.go

A quick follow up to improve the safety of the websocket implementation added in #155, before we expose it to the big bad internet.

fix: ensure websocket conns respect max duration

---

httpbin/cmd/cmd_test.go

Before these changes, running the test suite on macOS would pop up this network permission prompt a couple of times, for a split second each:

fix: silence annoying network permission popups on macos

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go

Noticed how inelegant the base64 handling was, mostly due to needing to hard code and handle the valid operations (encode and decode) in two different functions.

chore: minor refactor of base64 handling

---

README.md

Noticed the documentation for the EXCLUDE_HEADERS functionality was not correctly formatted, and took the opportunity to clean up the docs and expand the examples.

docs: update EXCLUDE_HEADERS documentation

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/httpbin.go
httpbin/responses.go
httpbin/static/index.html.tmpl
httpbin/static_assets.go

Each event is a "ping" that includes an incrementing integer ID and an integer Unix timestamp with millisecond resolution:
event: ping
data: {"id":9,"timestamp":1702417925258}
Fixes #150.

feat: add /sse endpoint to test Server-Sent Events

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go
httpbin/helpers_test.go
internal/testing/assert/assert.go

Fixes compatibility with the original httpbin by making the `/status` endpoint accept multiple, optionally weighted status codes to choose from.  Per the description in #145, this implementation attempts to match original httpbin's behavior:
- If not specified, weight is 1
- If specified, weights are parsed as floats, but there is no requirement that they sum to 1.0 or are otherwise limited to any particular range
Fixes #145.

feat: /status endpoint supports weighted choice

---

.codecov.yml
.github/workflows/ci.yaml
httpbin/websocket/websocket_autobahn_test.go

chore(ci): fix codecov configuration

---

README.md
kustomize/README.md
kustomize/kustomization.yaml
kustomize/resources.yaml

Adds a [kustomize application](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#application) that stands up a running instance of go-httpbin in a Kubernetes cluster.
This is useful to reference as a remote kustomization via your own kustomization, or can be used as:
`kustomize build github.com/mccutchen/go-httpbin/kustomize | kubectl apply -f -`
or even as:  `kubectl apply -k github.com/mccutchen/go-httpbin/kustomize`

feat: add a kustomize base to the repository

---

httpbin/helpers.go
httpbin/helpers_test.go

Add support for Fastly and Akamai custom headres to get a reasonable value of the client ip address.

feat: support Fastly and Akamai headers for client IP addr

---

.codecov.yml

Just noticed that codecov is penalizing us for limited coverage of the internal testing helper packages, which don't need coverage:
Hopefully this little tweak will fix that.

chore(ci): tweak codecov configuration

---

kustomize/resources.yaml

Add the `appProcotol` field to the k8s service for port name 'http'
This is recommended - and sometimes required - by third-party apps like Istio or Kuma
Official doc: https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol

add appProcotol to the k8s service for port name 'http'

---

httpbin/handlers.go
httpbin/handlers_test.go

Before this change, it was possible to bypass go-httpbin's allowed redirect domain configuration by passing an absolute URL without a scheme (e.g. `//evil.com`) to the `/redirect-to` endpoint.
Fixes #173.

fix: mitigate allowed redirect domain bypass

---

README.md
httpbin/cmd/cmd.go
httpbin/cmd/cmd_test.go
httpbin/handlers_test.go
httpbin/middleware.go
httpbin/middleware_test.go

This pr aims to give option to select one of the log formats text or json. It also introduces new flag `-log-format` to achieve.
I modified the tests so it should work out of the box. Also fixed some typos that I saw in general.
Please let me know if you also want me to modify README.
Closes #178

feat: implement log formatting and fix some typos

---

.github/workflows/ci.yaml

Looks like codecov.io now requires an explicit auth token, per [this failed upload](https://github.com/mccutchen/go-httpbin/actions/runs/10856421653/job/30131034321):
> [2024-09-13T21:34:57.324Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1478s.', code='throttled')}
> [2024-09-13T21:34:57.324Z] ['info'] Codecov will exit with status code 0. If you are expecting a non-zero exit code, please pass in the `-Z` flag

chore(ci): fix code coverage uploads

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/static/index.html.tmpl
httpbin/websocket/websocket_test.go
internal/testing/assert/assert.go

A handful of drive-by tweaks to the `/drip` implementation:
- Update docs to clarify intended uses (a helpful reminder for myself, if nothing else)
- Ensure all bad requests use standard JSON error responses
- Switch from binary to text content type
This also includes a small fix to the internal testing library, dropping the `assert.RoughDuration()` helper in favor of an updated generic `assert.RoughlyEqual()` implementation that works with the `time.Duration` type.

refactor: minor tweaks to `/drip` implementation

---

httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go
httpbin/helpers_test.go

Here we add [Server-Timing headers/trailers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing) to endpoints that let clients control response timing:
- `/delay` (header)
- `/drip` (header)
- `/sse` (trailer) 
Here's how this timing info is surfaced in the Firefox network inspector for the `/sse` endpoint:

feat: add `Server-Timing` headers/trailers where relevant

---

httpbin/cmd/cmd.go
httpbin/cmd/cmd_test.go
httpbin/handlers.go
httpbin/handlers_test.go
httpbin/httpbin.go
httpbin/options.go
httpbin/responses.go
httpbin/static/index.html.tmpl

Proposal of implementation of the feature request
- #114
----
I've submitted this for an initial round of review. 
I still have to add more cases to the test and add the endpoint to the index page, but first I'd like to receive feedback if this implementation goes in the right direction.
----
```bash
make run
curl http://127.0.0.1:8080/env
{
"env": {}
}
export HTTPBIN_A=a
export HTTPBIN_B=b
export HTTPBIN_123=123
make run
curl http://127.0.0.1:8080/env
{
"env": {
"HTTPBIN_123": "123",
"HTTPBIN_A": "a",
"HTTPBIN_B": "b"
}
}
```

feat: add /env endpoint to allow exposing operator-controlled info from the server

---

README.md
httpbin/cmd/cmd.go
httpbin/cmd/cmd_test.go

Fixes #194, which pointed out that we should allow configuring additional relevant options on the underlying [http.Server](https://pkg.go.dev/net/http#Server) without requiring users to build and push their own images.

feat: allow configuration of underlying `http.Server`

---

.github/workflows/release.yaml

Motivated by Docker's much more aggressive [rate limits on unauthenticated pulls of public images](https://docs.docker.com/docker-hub/usage/) going into effect on April 1:
> Unauthenticated users and users with a free Personal account have the following pull limits:
> * Unauthenticated users: 10 pulls/hour
Just gonna merge this and stamp a new release to see what happens, I guess?

ci: push to ghcr.io in addition to docker hub

---

httpbin/helpers.go

fix: `/ip` should not include port number

---

httpbin/handlers_test.go

Ugh, forgot I had auto-merge turned on for #212, so it went in before I could push a test.

fix: actually test fix for local port number in `/ip` response

---

httpbin/handlers_test.go

Really made a mess of fixing #211.  Here I realized that the test added in #213 (which tests #212) had a couple of small-ish issues:
- Missing `t.Parallel()` call, unnecessarily slowing down overall test suite
- No need to spin up new ephemeral test server, prefer the existing shared one

fix: small fixup to new `/ip` test case

---

README.md

This must have been broken since about #164, nearly 18 months ago.  Oops!

docs: fix build status badge in README

---

httpbin/cmd/cmd.go
httpbin/cmd/cmd_test.go
httpbin/digest/digest_test.go
httpbin/handlers.go
httpbin/handlers_test.go
httpbin/helpers.go
httpbin/helpers_test.go
httpbin/responses.go
httpbin/websocket/websocket_autobahn_test.go
httpbin/websocket/websocket_test.go

The results of running
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
See [modernize analyzer docs][1] for more info.
[1]: https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize

chore: modernize
